name: "Microsoft Defender & API Security"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '30 2 * * 6'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  msdo-analysis:
    name: Microsoft Defender (Static)
    runs-on: windows-latest
    timeout-minutes: 20
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Run Microsoft Security DevOps
        uses: microsoft/security-devops-action@v1
        id: msdo
        with:
          categories: 'secrets,iac,code'

      - name: Upload results to Security tab
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}
          category: microsoft-defender

  api-security-scan:
    name: APIsec Cloud Scan
    runs-on: ubuntu-latest
    timeout-minutes: 30
    needs: msdo-analysis
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: APIsec Security Scan
        uses: apisec-inc/apisec-run-scan@v1.0.6
        with:
          apisec-username: ${{ secrets.APISEC_USERNAME }}
          apisec-password: ${{ secrets.APISEC_PASSWORD }}
          apisec-project: ${{ secrets.APISEC_PROJECT_NAME }}
          sarif-result-file: "apisec-results.sarif"

      - name: Upload APIsec SARIF Report
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: ./apisec-results.sarif
          category: api-security